# Generated by Django 5.2.12 on 2026-03-05 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='shop',
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='part',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='spare.shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('seller', 'Seller')], default='user', max_length=10)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='spare.city')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('query_text', models.CharField(max_length=255)),
                ('normalized_query', models.CharField(blank=True, max_length=255)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_logs', to='spare.city')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SearchResultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('score', models.FloatField(default=0.0)),
                ('best_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spare.part')),
                ('search_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='spare.searchlog')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_result_logs', to='spare.shop')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.DeleteModel(
            name='ClickLog',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
