# Generated by Django 5.2.12 on 2026-03-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0002_enable_pgtrgm'),
        ('spare', '0002_remove_seller_shop_alter_part_options_and_more'),
    ]

    operations = [
    ]
